# Generated by Django 5.2.5 on 2025-08-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expirationsystem",
            fields=[
                (
                    "reference_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("product", models.CharField(max_length=100)),
                ("expiration_date", models.DateField()),
                ("quantity", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
